### ISSUE TITLE
WSL setup details (resolved: instructions in the comments)

### ISSUE THREAD

**Issue by colinbrace** [karpathy/llm.c#127]
Hi, 

I'm having trouble getting the CUDA code to execute.  I wanted to share my learnings thus far for this community, in case others are hitting this. 

For the CUDA version, the call in main() to cudaSetDevice(0) fails with 100 ("no CUDA-capable device is detected").   This is odd because I've had no problem with CUDA via python in my setup (which is WSL in Windows), a la:

```
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> print(torch.cuda.current_device())
0
```
plus nvidia-smi works fine.  During the zero-to-hero lessons, I would watch the utilization (and temperature!) race up as training ran.

To debug cudaSetDevice() failure in llm.c, I've noticed that if I link with cublas_static (and comment out the references to cublasLt, and hence cublsaLt is not pulled in), the cudaSetDevice(0) works fine a la:

```
[System]
Device 0: NVIDIA GeForce RTX 4060 Laptop GPU
```

Linking with cublasLt_static doesn't help (i.e. the CUDA fail again with 100).

I'm not sure why linking with cublas_static removes the error when using cublas functions, nor why cublasLt doesn't work with either static or shared.   I've repro'ed this static/shared behavior with more focused code using the sample/examples from the nvidia cublas github examples.  

If I crack this nut, I'll share updates.  In the meantime, suggestions welcome as well.

My environment:
`Linux xxxx 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
```

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.120                Driver Version: 537.58       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    On  | 00000000:01:00.0 Off |                  N/A |
| N/A   39C    P0              16W /  60W |      0MiB /  8188MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by colinbrace** [comment]
I've filed an issue with nvidia; I'll post back if I hear anything:

https://forums.developer.nvidia.com/t/device-not-found-for-shared-cublas-but-found-for-static-cublas-static/289614

**Comment by colinbrace** [comment]
Hi, I made progress on this one.  Almost there, but not 100%; read on.  I wanted to share learnings to far.  Not surprisingly, the whole static/shared library aspect is a red herring to getting things to work in Windows Subsystem for Linux (WSL).  

Here are repeatable steps to get `train_gpt2cu` to run in WSL. Really fun to see it execute!

1. Install Ubuntu fresh via wsl.  I'm sharing the version that I used.
```
~/dev/llm.c$ uname -r
5.15.146.1-microsoft-standard-WSL2
```

2. Get the latest bits and bytes and tools that you'll need
```
sudo apt update
sudo apt upgrade
sudo apt install gcc
sudo apt install python3-pip
```
3. Restart the Linux instance
4. Key point!  Get the *12.2* CUDA toolkit.  Neither 12.4 nor the default version a la (sudo apt install nvidia-cuda-toolkit) seems to work.  Follow the instructions here: https://developer.nvidia.com/cuda-12-2-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=runfile_local
5. Follow these instructions, per the above installer
```
 -   PATH includes /usr/local/cuda-12.2/bin
 -   LD_LIBRARY_PATH includes /usr/local/cuda-12.2/lib64, or, add /usr/local/cuda-12.2/lib64 to /etc/ld.so.conf and run ldconfig as root
```
6. Git clone away and follow the llm.c CUDA instructions.
8. Enjoy!

P.S. 
``python3 train_gpt2.py``

fails with

```
Running pytorch 2.2.2+cu121
using device: cuda
wrote gpt2_tokenizer.bin
loading weights from pretrained gpt: gpt2
loading cached tokens in data/tiny_shakespeare_val.bin
wrote gpt2_124M.bin
Traceback (most recent call last):
  File "/home/colin/dev/llm.c/train_gpt2.py", line 403, in <module>
    write_state(model, x, y, logits, loss, "gpt2_124M_debug_state.bin")
  File "/home/colin/dev/llm.c/train_gpt2.py", line 279, in write_state
    grads = {name: param.grad.cpu() for name, param in model.named_parameters()}
  File "/home/colin/dev/llm.c/train_gpt2.py", line 279, in <dictcomp>
    grads = {name: param.grad.cpu() for name, param in model.named_parameters()}
AttributeError: 'NoneType' object has no attribute 'cpu'
```

so there is on more (python?) dependency issue to sort out.  You can get around this, sadly, by commenting out the line

``#write_state(model, x, y, logits, loss, "gpt2_124M_debug_state.bin")``

This is obviously a silly solution; I'll need to spent more time later on resolving this one.  But getting close to running on WSL!

**Comment by dagelf** [comment]
If for some weird reason you're not on Ubuntu 22.04 ... Ubuntu used to have a notoriously old python so pretty sure that would be your issue. But even on Linux it was a struggle to get Pytorch and Cuda versions that match up, just a few months back. 

(incredible that Cuda works at all on WSL! Too many of the things I love about Linux, doesn't work on it, block devices, kernel options, network things, I've even had issues with pipes! I did love `coLinux`... too bad it didn't survive :cry: )

You should try to do a fresh pull though, this project is growing fast!

**Comment by colinbrace** [comment]
Resolved after a git fetch!  I didn't see any changes in train_gpt2.py that would have addressed, so perhaps elsewhere.  I didn't update the python version.

For the record here are the version of Ubuntu and Python in which this is working:

`Welcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.146.1-microsoft-standard-WSL2 x86_64)`

```
~/dev/llm.c$ python3 --version
Python 3.10.12
```

Thanks, dagelf, and tzzipproth for your suggestions and ideas.  WSL is now working end to end!
