### ISSUE TITLE
Suddenly "Out of memory" on train/python and train, test/CUDA on 4090

### ISSUE THREAD

**Issue by StoyanStAtanasov** [karpathy/llm.c#206]
Before yesterday I could run the project on my 4090. Yesterday evening already I got OOM. I thought It was WIP so I waited until today to create the issue.
```
(.venv) (base) user@home-pc:~/workspace/llm.c$ python train_gpt2.py
Running pytorch 2.2.2+cu121
using device: cuda
wrote gpt2_tokenizer.bin
loading weights from pretrained gpt: gpt2
Traceback (most recent call last):
  File "/home/user/workspace/llm.c/train_gpt2.py", line 359, in <module>
    model.to(device)
  File "/home/user/workspace/llm.c/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/home/user/workspace/llm.c/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/user/workspace/llm.c/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/user/workspace/llm.c/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/home/user/workspace/llm.c/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

And here is the CUDA - test
```
(.venv) (base) user@home-pc:~/workspace/llm.c$ make test_gpt2cu; ./test_gpt2cu
OpenMP found, compiling with OpenMP support
nvcc found, including CUDA builds
/usr/bin/nvcc -O3 --use_fast_math test_gpt2.cu -lcublas -lcublasLt -o test_gpt2cu
[System]
Device 0: NVIDIA GeForce RTX 4090
enable_tf32: 0
[GPT-2]
max_seq_len: 1024
vocab_size: 50257
num_layers: 12
num_heads: 12
channels: 768
num_parameters: 124439808
allocated 474 MiB for model parameters
[CUDA ERROR] at file train_gpt2.cu:1315:
out of memory
(.venv) (base) user@home-pc:~/workspace/llm.c$ 
```
and CUDA train
```
(.venv) (base) user@home-pc:~/workspace/llm.c$ make train_gpt2cu; ./train_gpt2cu
OpenMP found, compiling with OpenMP support
nvcc found, including CUDA builds
/usr/bin/nvcc -O3 --use_fast_math train_gpt2.cu -lcublas -lcublasLt -o train_gpt2cu
input dataset prefix: data/tiny_shakespeare
output log file: NULL
batch size B: 4
sequence length T: 1024
learning rate: 0.000300
val_loss_every: 20
val_max_batches: 20
sample_every: 20
genT: 64
[System]
Device 0: NVIDIA GeForce RTX 4090
Segmentation fault
```

**Comment by karpathy** [comment]
I don't think we changed anything. The python script was updated but the changes look harmless on a quick skim?

**Comment by StoyanStAtanasov** [comment]
I thought the same, but maybe someone else with a 4090 has the same issue. Maybe it's my PC. I will investigate further.

**Comment by StoyanStAtanasov** [comment]
OMG, restarted my PC and now it works. If anybody has the same issue - restart is the cure. Sorry to bother you guys.
